### ISSUE TITLE
Typo here. :)

### ISSUE THREAD

**Issue by JinnTonic** [sebh/Dx11Base#1]
https://github.com/sebh/Dx11Base/blob/b9e4a8f84c8ee63eef350608376756985f7711ce/DX11Base/Dx11Device.h#L251

**Comment by sebh** [comment]
Ah indeed, I will fix immediatly.
Thanks!

**Comment by sebh** [comment]
See https://github.com/sebh/Dx11Base/commit/36de2f2edf0aefe71580534d3def8c4e60e456f7
